### PR TITLE
Fixed bug with long player name

### LINKED ISSUE #94: Long player names break the layout
Long player names move the leader board out of screen.

Screenshot from 2021-07-15 15-08-07

### PR DESCRIPTION
**Pull request by JonathanDeul**
Fixed bug with long player name by adding a maximum length of 19 characters per name.

Resolves #94

### CODE REVIEW

**Comment by matthewejones** [comment]
The formatting still breaks if you change the size of the window

brokenstyle

**Comment by ChristophNiehoff** [comment]
I also think that limiting the characters per name is not the best solution.
* this does not have the best user experience.
* the number 19 might not be valid anymore, if the layout gets changed later.
* is that stable when zooming in (i.e. Ctrl-+)?

A believe a better and more responsive solution should use things like `max-width`, wrapping or maybe `text-overflow: ellipsis`.

**Comment by ChristophNiehoff** [comment]
@JonathanDeul I am afraid, but after merging the other PRs, this one got conflicts. Could you have a look at it?
Also: The copybutton-PR also made changes to the create-table. Could you merge `master` into this branch and see whether this PR has to be adapted?

**Comment by JonathanDeul** [comment]
> 
> 
> @JonathanDeul I am afraid, but after merging the other PRs, this one got conflicts. Could you have a look at it?
> Also: The copybutton-PR also made changes to the create-table. Could you merge `master` into this branch and see whether this PR has to be adapted?

I ll have a look at it in a few minutes!

File: src/client/pages/create.js [hunk 1]
```diff
@@ -166,7 +167,7 @@ class Create extends React.Component {
               <FormGroup row key={i}>
                 <Label for={`p${i}`} sm={2}>Name</Label>
                 <Col sm={10}>
-                  <Input autoComplete={"off"} type="text" invalid={_.isEmpty(this.state.names[i])} name={`p${i}`} id={`p${i}`} onChange={e => this.onNameUpdated(i, e)} value={this.state.names[i]} />
+                  <Input autoComplete={"off"} type="text" invalid={_.isEmpty(this.state.names[i])}  maxLength = "60" name={`p${i}`} id={`p${i}`} onChange={e => this.onNameUpdated(i, e)} value={this.state.names[i]} />
```
Comment (ChristophNiehoff) [inline src/client/pages/create.js:185]: Why do we still need a `maxLength`?

**Review by ChristophNiehoff — CHANGES_REQUESTED** [review]
I like the responsive behavior.
But in the create-table also the second column with the links gets cut off. Actually, Iiked it the way it was before (as it showed the users what these links were...).  We can also think about making the whole create table wider...

**Comment by ChristophNiehoff** [comment]
@JonathanDeul  I think the fix is great for the create table! 

But for the leader board the name column is too narrow. When using the default names "Player 1", "Player 2" etc. one cannot distinguish them. Also the `(you)` is not visible anymore...

Screenshot from 2021-07-21 09-35-18

File: src/client/components/leaderboard/leaderboard.js [hunk 2]
```diff
@@ -20,33 +20,36 @@ class Leaderboard extends React.Component {
...
-                <th>#</th>
-                <th>Name</th>
-                <th>Passed</th>
-                <th>Card</th>
-                <th>Score</th>
+        <Table size="sm">
+          <thead>
+            <tr>
+              <th>Name</th>
+              <th></th>
```
Comment (ChristophNiehoff) [inline src/client/components/leaderboard/leaderboard.js:27]: You added this empty column such that the `(you)` does not get cut off, right?

But this still leads to strangely cut off player names

Screenshot from 2021-07-27 14-44-57

I would propose the following:
1. remove the empty column
2. add the `(you)` in a new line (e.g. by wrapping it in a `div`).

```js
<td>
  <div className={parseInt(this.props.playerID) === idx ? "ownPlayername" : "otherPlayername"}>
    {this.props.names[idx]}
  </div>
  {parseInt(this.props.playerID) === idx && <div><strong>(you)</strong></div>}
</td>
```

Then it would look like

Screenshot from 2021-07-27 14-45-13

**Review by ChristophNiehoff — CHANGES_REQUESTED** [review]

**Review by ChristophNiehoff — APPROVED** [review]
