### PR TITLE
Fix not all cornucopia cards

### LINKED ISSUE #133: Not all Cornucopia cards are used
All games start with AuthN3, but AuthN2 should also be available. Could it be that EoP's `INVALID_CARDS` also apply to Cornucopia?

### LINKED ISSUE #140: Some cards are not visible
On current master, the deck contains the card `E2` bu this is not visible. Maybe it's got something to do with `B2` being in `STARTING_CARD_MAP` and `INVALID_CARDS` at the same time? Should `INVALID_CARDS` rather contain `E2`?

Are `STARTIND_CARD_MAP` and `INVALID_CARDS` correct for all suits?

Screenshot from 2021-08-13 11-55-09

### PR DESCRIPTION
**Pull request by matthewejones**
I think the problem may have actually been to do with just the starting card. I've changed this and it now starts with the 2 of each suit as expected when playing cornucopia

Resolves #133, resolves #140

### CODE REVIEW

File: src/game/utils.js [hunk 1]
```diff
@@ -54,10 +54,13 @@ export function shuffleCards(ctx, startingCard) {
 export function setupGame(ctx, setupData) {
   const startSuit = (setupData) ? setupData.startSuit || DEFAULT_START_SUIT : DEFAULT_START_SUIT;
   const gameMode = setupData ? setupData.gameMode || DEFAULT_GAME_MODE : DEFAULT_GAME_MODE;
-  const startingCard = STARTING_CARD_MAP[startSuit];
-  // remove invalid cards
-  if (!isGameModeCornucopia(gameMode)) {
+  let startingCard;
+
+  if (isGameModeCornucopia(gameMode)) {
+    startingCard = startSuit + '2';
```
Comment (ChristophNiehoff) [inline src/game/utils.js:60]: I believe it would be better to have the same logic for EoP and Cornucopia, i.e. there should also be a `STARTING_CARD_MAP` for Cornucopia. And maybe even an (empty) `INVALID_CARDS`. It would be better to have consistent solutions.

**Review by ChristophNiehoff — CHANGES_REQUESTED** [review]

File: src/game/utils.js (hunk 1 above)
Comment (ChristophNiehoff) [reply src/game/utils.js:60]: @matthewejones   While you are at it, please take the opportunity and also have a look at https://github.com/dehydr8/elevation-of-privilege/issues/140

**Comment by matthewejones** [comment]
The way I did it in the end was adding another dimension to `INVALID_CARDS` and `STARTING_CARD_MAP`
Having it like this avoids having to introduce if statements in `setupGame`

Also now resolves #140

File: src/utils/constants.js [hunk 2]
```diff
@@ -1,18 +1,28 @@
...
 export const DEFAULT_GAME_MODE = "Elevation of Privilege";
+export const INVALID_CARDS = {[GAMEMODE_EOP]: ['E2', 'T2', 'T3', 'T4'], [GAMEMODE_CORNUCOPIA]: []};
 export const STARTING_CARD_MAP = {
-  'D': 'D2',
-  'E': 'E3',
-  'C': 'C2',
-  'B': 'B2',
-  'A': 'A2',
-  'T': 'T5'
+  [GAMEMODE_EOP]: {
```
Comment (ChristophNiehoff) [inline src/utils/constants.js:10]: This breaks https://github.com/matthewejones/elevation-of-privilege/blob/13423f19533288308a7473aee6a311626565e4e7/src/client/pages/create.js#L215 

As a result the dropdown for choosing a start suit in the create page is empty.  Better check all occurances of `STARTING_CARD_MAP` and `INVALID_CARDS`

**Review by ChristophNiehoff — CHANGES_REQUESTED** [review]

File: src/utils/constants.js (hunk 2 above)
Comment (matthewejones) [reply src/utils/constants.js:10]: I just saw this after I posted it. I pushed a commit that should fix this: https://github.com/dehydr8/elevation-of-privilege/pull/138/commits/314a3f560b7524894d72f91910f9d73483a527d5

**Review by ChristophNiehoff — APPROVED** [review]
